apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: event-management-service
spec:
  minReplicas: 2
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 500
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 500
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-management-service
