apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: event-management-service
spec:
  minReplicas: 2
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: 500
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: 500
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-management-service
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: event-query
spec:
  minReplicas: 2
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: 500
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: 500
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-query

