apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: event-management-service
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: event-management-service
      project: event-management-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: event-query
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: event-query
      project: event-management-service

