apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: event-management-service-vs
spec:
  gateways:
    - zing-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /v1/event-management/
      route:
        - destination:
            host: event-management-service-public
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: event-query
    project: event-management-service
  name: event-query-vs
spec:
  gateways:
    - zing-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /zenoss.cloud.event_query.v2.EventQueryService/
        - uri:
            prefix: /v1/events/
        - uri:
            regex: /v1/events:(search|getBulk|count|frequency)
      route:
        - destination:
            host: event-query-public
            port:
              number: 80
