#
# This compose file is intended for integration testing
#
version: "3.3"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zing-user
      MONGO_INITDB_ROOT_PASSWORD: .H1ddenPassw0rd.
    ports:
      - 27018:27018
    networks:
      default:
        aliases:
          - zing-mongodb
  redis:
    restart: "no"
    image: redis
    ports:
      - "6379"
    command: redis-server --appendonly yes
  test:
    privileged: true
    image: zenoss/zenkit-build:${ZENKIT_BUILD_VERSION}
    security_opt:
      - seccomp:unconfined
    depends_on:
      - mongodb
      - redis
    environment:
      EVENT_MANAGEMENT_SERVICE_GCLOUD_MEMORYSTORE_ADDRESS: redis:6379
      EVENT_MANAGEMENT_SERVICE_GCLOUD_MONGO_ADDRESS: mongodb
