apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management-service
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        istio.io/rev: "asm-managed-stable"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-query
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
      labels:
        istio.io/rev: "asm-managed-stable"